*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5166,6 +5166,83 @@ _ACEOF
 fi
 
 
+echo "$as_me:$LINENO: checking for JNI_CreateJavaVM in -ljava" >&5
+echo $ECHO_N "checking for JNI_CreateJavaVM in -ljava... $ECHO_C" >&6
+if test "${ac_cv_lib_java_JNI_CreateJavaVM+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ljava $JAVALIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char JNI_CreateJavaVM ();
+int
+main ()
+{
+JNI_CreateJavaVM ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_java_JNI_CreateJavaVM=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_java_JNI_CreateJavaVM=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_java_JNI_CreateJavaVM" >&5
+echo "${ECHO_T}$ac_cv_lib_java_JNI_CreateJavaVM" >&6
+if test $ac_cv_lib_java_JNI_CreateJavaVM = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBJAVA 1
+_ACEOF
+
+  LIBS="-ljava $LIBS"
+
+fi
+
+
+case "${host_os}" in
+	darwin* )
+		LIBS="$LIBS $JAVALIBS"
+		cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBJAVA 1
+_ACEOF
+
+		{ echo "$as_me:$LINENO: WARNING: Trying to use OS X framework..." >&5
+echo "$as_me: WARNING: Trying to use OS X framework..." >&2;}
+
+	;;
+esac
+
 ac_ext=cc
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
