*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3099,76 +3099,6 @@ See \`config.log' for more details." >&2;}
 fi
 
 
-echo "$as_me:$LINENO: checking for dWorldStep in -lode" >&5
-echo $ECHO_N "checking for dWorldStep in -lode... $ECHO_C" >&6
-if test "${ac_cv_lib_ode_dWorldStep+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lode -lstdc++ $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char dWorldStep ();
-int
-main ()
-{
-dWorldStep ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_ode_dWorldStep=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_ode_dWorldStep=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_ode_dWorldStep" >&5
-echo "${ECHO_T}$ac_cv_lib_ode_dWorldStep" >&6
-if test $ac_cv_lib_ode_dWorldStep = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBODE 1
-_ACEOF
-
-  LIBS="-lode $LIBS"
-
-else
-  { { echo "$as_me:$LINENO: error: Missing ODE library -- see http://opende.sourceforge.net
-See \`config.log' for more details." >&5
-echo "$as_me: error: Missing ODE library -- see http://opende.sourceforge.net
-See \`config.log' for more details." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-
 echo "$as_me:$LINENO: checking for XML_ParserCreate in -lexpat" >&5
 echo $ECHO_N "checking for XML_ParserCreate in -lexpat... $ECHO_C" >&6
 if test "${ac_cv_lib_expat_XML_ParserCreate+set}" = set; then
@@ -3891,6 +3821,76 @@ ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
+
+
+echo "$as_me:$LINENO: checking for dWorldStep in -lode" >&5
+echo $ECHO_N "checking for dWorldStep in -lode... $ECHO_C" >&6
+if test "${ac_cv_lib_ode_dWorldStep+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lode -lstdc++ $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char dWorldStep ();
+int
+main ()
+{
+dWorldStep ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_ode_dWorldStep=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_ode_dWorldStep=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_ode_dWorldStep" >&5
+echo "${ECHO_T}$ac_cv_lib_ode_dWorldStep" >&6
+if test $ac_cv_lib_ode_dWorldStep = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBODE 1
+_ACEOF
+
+  LIBS="-lode $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: Missing ODE library -- see http://opende.sourceforge.net
+See \`config.log' for more details." >&5
+echo "$as_me: error: Missing ODE library -- see http://opende.sourceforge.net
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
 echo "$as_me:$LINENO: checking for pushEnvironmentNew in -lpush" >&5
