- mux mpeg streams with libavformat instead of doing it ourselves.    this is an extra library dependency, but anyone with ffmpeg should    have both lavc and lavf anyway. - use lavc img_convert instead of our own for colorspace conversion    (it's still just a huge ugly C function, but now it's in an external library    that supports lots more pixel formats). - make a pile of globals in breve.cc static. - don't bother trying to drop our mutex after calling brQuit() in workerThread    (this braindamage was entirely my fault..) - move the png snapshot function to breveFunctionsImage.cc - keep simulation.{mpeg|png} out of repository.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8980,6 +8980,80 @@ _ACEOF
 fi
 
 
+echo "$as_me:$LINENO: checking for av_write_frame in -lavformat" >&5
+echo $ECHO_N "checking for av_write_frame in -lavformat... $ECHO_C" >&6
+if test "${ac_cv_lib_avformat_av_write_frame+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lavformat  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char av_write_frame ();
+int
+main ()
+{
+av_write_frame ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_avformat_av_write_frame=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_avformat_av_write_frame=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_avformat_av_write_frame" >&5
+echo "${ECHO_T}$ac_cv_lib_avformat_av_write_frame" >&6
+if test $ac_cv_lib_avformat_av_write_frame = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBAVFORMAT 1
+_ACEOF
+
+  LIBS="-lavformat $LIBS"
+
+fi
+
+
 echo "$as_me:$LINENO: checking for OSMesaCreateContext in -lOSMesa" >&5
 echo $ECHO_N "checking for OSMesaCreateContext in -lOSMesa... $ECHO_C" >&6
 if test "${ac_cv_lib_OSMesa_OSMesaCreateContext+set}" = set; then
@@ -10086,9 +10160,9 @@ if test "$ac_cv_lib_sndfile_sf_open" != yes; then
 echo "$as_me: WARNING: libsndfile not found. building without audio support." >&2;}
 fi
 
-if test "$ac_cv_lib_avcodec_avcodec_init" != yes; then
-	{ echo "$as_me:$LINENO: WARNING: libavcodec not found. building without movie export support." >&5
-echo "$as_me: WARNING: libavcodec not found. building without movie export support." >&2;}
+if test "$ac_cv_lib_avformat_av_write_frame" != yes; then
+	{ echo "$as_me:$LINENO: WARNING: libavformat not found. building without MPEG support." >&5
+echo "$as_me: WARNING: libavformat not found. building without MPEG support." >&2;}
 fi
 
 if test "x$_have_jvm" = x ; then
