*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2705,7 +2705,7 @@ fi
 case "${host_os}" in
 	darwin* )
 
-		AUDIOLIBS="-framework CoreAudio -framework AudioToolbox"
+		AUDIOLIBS="-framework vecLib -framework CoreAudio -framework AudioToolbox"
 		JAVALIBS="-framework JavaVM"
 		JAVAINCS="-I/System/Library/Frameworks/JavaVM.framework/Headers"
 		GLLIBS="-framework OpenGL -framework GLUT -framework AppKit"
@@ -5172,7 +5172,7 @@ if test "${ac_cv_lib_java_JNI_CreateJavaVM+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-Xlinker -rpath /usr/java/j2sdk1.4.0_01/jre/lib/i386/client -Xlinker -rpath /usr/java/j2sdk1.4.0_01/jre/lib/i386 -ljava $JAVALIBS $LIBS"
+LIBS="-ljava $JAVALIBS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -5230,6 +5230,134 @@ _ACEOF
 fi
 
 
+echo "$as_me:$LINENO: checking for cblas_ccopy in -lgslcblas" >&5
+echo $ECHO_N "checking for cblas_ccopy in -lgslcblas... $ECHO_C" >&6
+if test "${ac_cv_lib_gslcblas_cblas_ccopy+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgslcblas  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char cblas_ccopy ();
+int
+main ()
+{
+cblas_ccopy ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_gslcblas_cblas_ccopy=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_gslcblas_cblas_ccopy=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_gslcblas_cblas_ccopy" >&5
+echo "${ECHO_T}$ac_cv_lib_gslcblas_cblas_ccopy" >&6
+if test $ac_cv_lib_gslcblas_cblas_ccopy = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBGSLCBLAS 1
+_ACEOF
+
+  LIBS="-lgslcblas $LIBS"
+
+fi
+
+
+echo "$as_me:$LINENO: checking for gsl_rng_alloc in -lgsl" >&5
+echo $ECHO_N "checking for gsl_rng_alloc in -lgsl... $ECHO_C" >&6
+if test "${ac_cv_lib_gsl_gsl_rng_alloc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgsl  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char gsl_rng_alloc ();
+int
+main ()
+{
+gsl_rng_alloc ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_gsl_gsl_rng_alloc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_gsl_gsl_rng_alloc=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_gsl_gsl_rng_alloc" >&5
+echo "${ECHO_T}$ac_cv_lib_gsl_gsl_rng_alloc" >&6
+if test $ac_cv_lib_gsl_gsl_rng_alloc = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBGSL 1
+_ACEOF
+
+  LIBS="-lgsl $LIBS"
+
+fi
+
+
 case "${host_os}" in
 	darwin* )
 		LIBS="$LIBS $JAVALIBS"
@@ -5237,8 +5365,6 @@ case "${host_os}" in
 #define HAVE_LIBJAVA 1
 _ACEOF
 
-		{ echo "$as_me:$LINENO: WARNING: Trying to use OS X framework..." >&5
-echo "$as_me: WARNING: Trying to use OS X framework..." >&2;}
 
 	;;
 esac
