*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2782,6 +2782,14 @@ _ACEOF
 
 		;;
 
+
+	openbsd* )
+		GLLIBS="-lglut -lGL -lGLU -lXmu -lm -lutf8"
+		CPPFLAGS="$(CPPFLAGS) -I/usr/local/include -I/usr/X11R6/include"
+		LDFLAGS="$(LDFLAGS) -L/usr/local/lib -L/usr/X11R6/lib"
+
+		;;
+
 	*)
 
 		;;
@@ -4846,70 +4854,6 @@ _ACEOF
 fi
 
 
-echo "$as_me:$LINENO: checking for OSMesaCreateContext in -lOSMesa" >&5
-echo $ECHO_N "checking for OSMesaCreateContext in -lOSMesa... $ECHO_C" >&6
-if test "${ac_cv_lib_OSMesa_OSMesaCreateContext+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lOSMesa $GLLIBS $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char OSMesaCreateContext ();
-int
-main ()
-{
-OSMesaCreateContext ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_OSMesa_OSMesaCreateContext=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_OSMesa_OSMesaCreateContext=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_OSMesa_OSMesaCreateContext" >&5
-echo "${ECHO_T}$ac_cv_lib_OSMesa_OSMesaCreateContext" >&6
-if test $ac_cv_lib_OSMesa_OSMesaCreateContext = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBOSMESA 1
-_ACEOF
-
-  LIBS="-lOSMesa $LIBS"
-
-fi
-
-
 echo "$as_me:$LINENO: checking for tputs in -ltermcap" >&5
 echo $ECHO_N "checking for tputs in -ltermcap... $ECHO_C" >&6
 if test "${ac_cv_lib_termcap_tputs+set}" = set; then
@@ -5579,6 +5523,71 @@ ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+
+echo "$as_me:$LINENO: checking for OSMesaCreateContext in -lOSMesa" >&5
+echo $ECHO_N "checking for OSMesaCreateContext in -lOSMesa... $ECHO_C" >&6
+if test "${ac_cv_lib_OSMesa_OSMesaCreateContext+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lOSMesa $GLLIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char OSMesaCreateContext ();
+int
+main ()
+{
+OSMesaCreateContext ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_OSMesa_OSMesaCreateContext=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_OSMesa_OSMesaCreateContext=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_OSMesa_OSMesaCreateContext" >&5
+echo "${ECHO_T}$ac_cv_lib_OSMesa_OSMesaCreateContext" >&6
+if test $ac_cv_lib_OSMesa_OSMesaCreateContext = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBOSMESA 1
+_ACEOF
+
+  LIBS="-lOSMesa $LIBS"
+
+fi
 
 
 # Checks for header files.
